### PR TITLE
Remove cache

### PR DESCRIPTION
**Pull request by nicoonoclaste**
This is actually much faster (esp. if your GPG key sits on a HSM):
- no cache is read/decrypted on startup;
- there is no need to read and hash all files on startup to update the cache.

However, this changes (slightly) autopass' behaviour: since the data is not parsed in advance, invalid/unparseable entries cannot be hilighted in rofi.

### CODE REVIEW

**Comment by nicoonoclaste** [comment]
The cache file is, by the way, a ~~potential~~ security issue:
another user might well create `/tmp/autopass-${USER}.cache` (in most systems, `/tmp` is shared and world-writeable) and write there an evil Ruby marshalled object, encrypted to the user's public key.

**Comment by repomaa** [comment]
thanks for the input.
1. The cache is absolutely necessary. Otherwise sorting of the rofi entries by best matching entries for window title won't work.
2. You're right about the security issue. The cache can be written anywhere though (it's configurable). You can write it to ${HOME}/.cache/autopass for instance and have no security issue. I'm tempted to change this as default.
3. It's slow only if the cache doesn't exist already. After that it's as fast as with your pr. But has the advantage i stated in 1.

**Comment by nicoonoclaste** [comment]
1. This indeed breaks the `window` attribute, but not sorting for a match based on the filename.
2. I'm aware it is configurable, but the default is definitely unsafe.
3. Even if the cache exists, those actions are taken on startup:
   - the cache is decrypted and unmarshalled;
   - `autopass` walks through all files in the pass db, takes a SHA256 hash, and if needed decrypts and parses.
   
   As mentioned initially, decryption is slow if your decryption key is stored on a HSM (Yubikey, smartcard, ...)

**Comment by nicoonoclaste** [comment]
PS: Replacing the `window` attribute with a single non-encrypted file that contains similar data would preserve that functionality too.

**Comment by repomaa** [comment]
Yes I'm aware of that. But this would require the user to add files to his/her password-store which i'm not willing to enforce. Sorry but I won't merge this. If you want you can check out carnager/rofi-pass. It's very similar and doesn't use a cache (also doesn't have the window feature).

**Comment by nicoonoclaste** [comment]
@jreinert Is that a EWONTFIX for all the other issues I raised (esp. security-wise) ?

**Comment by repomaa** [comment]
@nbraud no, security wise it's a good notion and i'll change the default cache location

**Comment by nicoonoclaste** [comment]
@jreinert Changing the default file location is barely more than a band-aid, though  :-(

**Pull request closed without merging**
